### ISSUE TITLE
Plain javascript usage

### ISSUE THREAD

**Issue by oshihirii** [howlowck/words-to-num#1]
Hello,

If you had the time/interest, would you mind confirming if [this jsFiddle](
https://jsfiddle.net/rwone/c3y3qp8r) (edit:  [updated fiddle covering more scenarios](https://jsfiddle.net/rwone/4zgqmsk0)) is a valid implementation of your great package in plain Javascript?  (All the test numbers I have put into it seem to work)  

Thank You!

**Comment by howlowck** [comment]
Hey!  yea, you can just copy and paste it into your code. 
But this library uses UMD pattern so you can just refer to the build/main.js file, and load it into your app.
