### ISSUE TITLE
NaN result

### ISSUE THREAD

**Issue by bhoomika911** [howlowck/words-to-num#3]
Hi howlowck...

This is a great package for word to number conversion.I have some problem.

Example:

"One Hundred" => 100 .     // Output as expected
"Serving One Hundred" => NaN     //Return NaN when there is other string like "Serving"

Can you please help?

**Comment by oshihirii** [comment]
What do you want:

"Serving One Hundred"

to return?  

Can you modify the string so that what is fed to WtoN is only numbers as words?
